version: '3'
services:
  docker-node-mongo:
    image: "docker-node-mongo"
    build: .
    command: "node app.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml