{
 "title": "My App Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "The total number of processed requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_request_operations_total" }
   ]
  },
  {
   "title": "The total number of added tasks VS The total number of deleted tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_request_add_Tasks_total[5m])"
    },
    {
     "expr": "rate(node_request_delete_Tasks_total[5m])"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_system_seconds_total[5m])"
    }
   ]
  }
 ]
}