name : Test Palindrome

on: 
  push:
    branches: [ master ]

jobs:

  build:
    name: Test Build
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x 
      
      - run: npm ci
      
      - run: npm test
      