name : Test Palindrome

on: 
  push:
    branches: [ master ]

jobs:

  build:
    name: Test Build
    runs-on: ubuntu-latest 
    steps:

      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12' 
      - run: npm install
      - run: npm test
      