name : Test Palindrome with Jest

on: 
  push:
    branches: [ master ]

jobs:

  build:
    name: Test Build
    runs-on: ubuntu-latest 
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12        
      
      - name: Run a one-line script
        uses: actions/checkout@v2
        
      - run: yarn install
      - run: yarn test